<?php 
// $family_referral_map['fields'][$i]['name'];
$family_referral_map = array(
	'key' => 'group_5b49a61b22b9d',
	'title' => 'family-referral',
	'fields' => array(
		array(
			'key' => 'field_5b49a684fe226',
			'label' => 'תאריך',
			'name' => 'family_referral_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 0,
		),
		array(
			'key' => 'field_5b601904c33a9',
			'label' => 'שם משפחה',
			'name' => 'family_referral_family_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b60192dc33aa',
			'label' => 'אשה - שם פרטי',
			'name' => 'family_referral_woman_firstname',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b601969c33ab',
			'label' => 'גבר - שם פרטי',
			'name' => 'family_referral_man_firstname',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b6018d4c33a8',
			'label' => 'קוד',
			'name' => 'family_referral_code',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5b4cfc3f05e8b',
			'label' => 'מלווה',
			'name' => 'family_referral_team',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b4cfc1805e8a',
			'label' => 'סטטוס',
			'name' => 'family_referral_status',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'התקבלה פניה אך טרם התבצע בירור' => 'התקבלה פניה אך טרם התבצע בירור',
				'בבירור עם גורם מפנה' => 'בבירור עם גורם מפנה',
				'בבירור עם המשפחה' => 'בבירור עם המשפחה',
				'אחר' => 'אחר',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5b60ee462b2f6',
			'label' => 'נייד אשה',
			'name' => 'family_referral_cell_woman',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b60ee852b2f7',
			'label' => 'נייד גבר',
			'name' => 'family_referral_cell_man',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b49a634fe225',
			'label' => 'גורם מפנה',
			'name' => 'family_referral_initiator',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b60eeaa2b2f8',
			'label' => 'גיל אשה',
			'name' => 'family_referral_age_woman',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5b60eee32b2f9',
			'label' => 'גיל גבר',
			'name' => 'family_referral_age_man',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5b49a6defe227',
			'label' => 'סטטוס משפחתי',
			'name' => 'family_referral_merita_status',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'נשואים' => 'נשואים',
				'חיים יחד' => 'חיים יחד',
				'פרוד/ה' => 'פרוד/ה',
				'גרוש/ה' => 'גרוש/ה',
				'אלמן/ה' => 'אלמן/ה',
				'נשואה בעל בכלא' => 'נשואה בעל בכלא',
				'רווק/ה' => 'רווק/ה',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5b60f01ad7edc',
			'label' => 'מספר ילדים',
			'name' => 'family_referral_num_kids',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5b5ad379597b7',
			'label' => 'סיבה מרכזית',
			'name' => 'family_referral_reason',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'קשיים בהתנהלות כלכלית שוטפת' => 'קשיים בהתנהלות כלכלית שוטפת',
				'הכנסות נמוכות' => 'הכנסות נמוכות',
				'אבטלה או תעסוקה בלתי איכותית' => 'אבטלה או תעסוקה בלתי איכותית',
				'מצב משפחתי רעוע' => 'מצב משפחתי רעוע',
				'קשיים של ילדים' => 'קשיים של ילדים',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5b60f13c0dca3',
			'label' => 'מקום עבודה אשה',
			'name' => 'family_refferal_woman_workplace',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b60f17f0dca4',
			'label' => 'מקום עבודה גבר',
			'name' => 'family_refferal_man_workplace',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b60f1b30dca5',
			'label' => 'אומדן חובות',
			'name' => 'family_referral_debts',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5b5ad41b597b8',
			'label' => 'לקוחה של הרווחה',
			'name' => 'family_referral_os_client',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'כן' => 'כן',
				'לא' => 'לא',
				'היתה בעבר' => 'היתה בעבר',
			),
			'default_value' => array(
				0 => 'כן',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5b60f244a8669',
			'label' => 'השתתפה בתכנית שיפור',
			'name' => 'family_referral_prev_plan',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5b60f308c6106',
			'label' => 'באיזה תכנית השתתפה',
			'name' => 'family_referral_prev_plan_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b60f33bc6107',
			'label' => 'האם התבצעה שיחת טלפון',
			'name' => 'family_referral_phone call',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5b60f37cc6108',
			'label' => 'האם נקבע אינטייק',
			'name' => 'family_referral_intake_set',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5b60f3d080ac9',
			'label' => 'תאריך אינטייק',
			'name' => 'family_referral_intake_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5b5eb53bcd99f',
			'label' => 'החלטת מנהלת',
			'name' => 'family_referral_mgr_decision',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'קבלה לתוכנית' => 'קבלה לתוכנית',
				'דחיה' => 'דחיה',
				'המשך בירור' => 'המשך בירור',
				'מעבר לכתף לכתף' => 'מעבר לכתף לכתף',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5b5eb5aacd9a0',
			'label' => 'הסבר החלטת מנהלת',
			'name' => 'family_referral_mgr_explain',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 2,
			'new_lines' => '',
		),
		array(
			'key' => 'field_5b5eb5ffcd9a1',
			'label' => 'החלטת משפחה',
			'name' => 'family_referral_family_decision',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'הצטרפות לתכנית' => 'הצטרפות לתכנית',
				'ויתור' => 'ויתור',
				'נדחתה ע"י התכנית' => 'נדחתה ע"י התכנית',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5b5eb6b3cd9a2',
			'label' => 'הסבר החלטת משפחה',
			'name' => 'family_referral_family_explain',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'digma_referrals',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'digma_families',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'author',
		4 => 'format',
		5 => 'page_attributes',
		6 => 'featured_image',
		7 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
);

?>